# rlastudio.co and rodrigolarrain.com (plus www) permanently redirect to rodlarrain.com
[[redirects]]
  from = "https://rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://rodrigolarrain.com/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rodrigolarrain.com/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rodrigolarrain.com/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.rodrigolarrain.com/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true
