# rlastudio.co and www.rlastudio.co permanently redirect to rodlarrain.com
[[redirects]]
  from = "https://rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.rlastudio.co/*"
  to = "https://rodlarrain.com/:splat"
  status = 301
  force = true
